# Generated by Django 5.1.6 on 2025-06-12 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsireca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsireca.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='AccesoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresar', models.BooleanField(default=True)),
                ('editar', models.BooleanField(default=True)),
                ('ver', models.BooleanField(default=True)),
                ('eliminar', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsireca.modulo')),
                ('perfilpersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsireca.perfilpersona')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100, verbose_name='1er Apellido')),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True, verbose_name='2do Apellido')),
                ('extranjero', models.BooleanField(default=False)),
                ('identificacion', models.CharField(blank=True, max_length=13, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('madre', models.CharField(blank=True, max_length=100, null=True)),
                ('padre', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle Principal')),
                ('direccion2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle Secundaria')),
                ('num_direccion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de Residencia')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefonos Moviles')),
                ('telefono_conv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefonos Fijos')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correos Electronicos')),
                ('email1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correos Electronicos')),
                ('email2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correos Electronicos')),
                ('emailinst', models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo Institucional')),
                ('reestablecer', models.BooleanField(default=False)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_res', models.DateTimeField(blank=True, null=True)),
                ('fechaingreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsireca.canton', verbose_name='Canton de Nacimiento')),
                ('cantonresid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CantondeResidencia', to='appsireca.canton', verbose_name='Canton de Residencia')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsireca.nacionalidad')),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsireca.parroquia', verbose_name='Parroquia')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsireca.provincia', verbose_name='Provincia de Nacimiento')),
                ('provinciaresid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProvinciadeResidencia', to='appsireca.provincia', verbose_name='Provincia de Residencia')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsireca.sexo')),
                ('tipoidentificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsireca.tipoidentificacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='perfilpersona',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsireca.persona'),
        ),
    ]
